# Generated by Django 4.0.4 on 2022-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaktor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'list_package',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
